import { useCallback, useEffect, useMemo, useState } from 'react';
import type { KnowledgeArticle } from '../../types';
import { createKnowledgeArticle, deleteKnowledgeArticle, getKnowledgeArticles, updateKnowledgeArticle, uploadKnowledgeAttachment } from '../../services/knowledgeApi';
import { Button } from '../layout/Button';
import { Modal } from '../layout/Modal';
import { useAssistantContext } from '../../hooks/useAssistantContext';

const EMPTY:Partial<KnowledgeArticle>={title:'',content:'',category:'General',tags:[],attachments:[]};
export function KnowledgePage({consultationMode}:{consultationMode:boolean}){
  const[items,setItems]=useState<KnowledgeArticle[]>([]);const[search,setSearch]=useState('');const[draft,setDraft]=useState<Partial<KnowledgeArticle>|null>(null);const[selected,setSelected]=useState<KnowledgeArticle|null>(null);const[uploading,setUploading]=useState(false);const[error,setError]=useState('');
  useAssistantContext(selected?{type:'knowledge',id:String(selected.id),label:selected.title,data:{category:selected.category,tags:selected.tags}}:null);
  const load=useCallback(async()=>{try{const response=await getKnowledgeArticles();setItems(response.items);}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo cargar la base.');}},[]);useEffect(()=>{void load();},[load]);
  const visible=useMemo(()=>{const q=search.toLowerCase().trim();return items.filter(item=>!q||`${item.title} ${item.category} ${item.tags.join(' ')} ${item.contentText}`.toLowerCase().includes(q));},[items,search]);
  const save=async()=>{if(!draft?.title?.trim()||!draft.content?.trim())return;if(draft.id)await updateKnowledgeArticle(draft.id,draft);else await createKnowledgeArticle(draft);setDraft(null);await load();};
  const file=async(value?:File)=>{if(!value)return;setUploading(true);try{const base64=await read(value);const response=await uploadKnowledgeAttachment({name:value.name,mimeType:value.type||mime(value.name),base64});setDraft(current=>({...current!,attachments:[...(current?.attachments||[]),response.attachment]}));}finally{setUploading(false);}};
  return <section className="view active knowledge-page"><div className="knowledge-hero card"><div><span className="eyebrow">Documentación interna</span><h2>Base de conocimiento</h2><p>Procedimientos propios que el Asistente TechAsset consulta antes de responder.</p></div><Button variant="primary" disabled={consultationMode} onClick={()=>setDraft({...EMPTY})}>+ Nuevo artículo</Button></div>{error&&<div className="tool-error">{error}</div>}<div className="knowledge-toolbar card"><input className="input" type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar procedimiento, equipo, WiFi, proyector…"/><span>{visible.length} artículos</span></div><div className="knowledge-grid">{visible.map(item=><article className="card knowledge-card" key={item.id}><header><span>{item.category||'General'}</span><small>{date(item.updatedAt)}</small></header><h3>{item.title}</h3><p>{item.contentText.slice(0,220)}{item.contentText.length>220?'…':''}</p><div className="ticket-tags">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div><footer><Button onClick={()=>setSelected(item)}>Leer</Button><Button disabled={consultationMode} onClick={()=>setDraft({...item})}>Editar</Button><Button disabled={consultationMode} onClick={async()=>{if(!window.confirm(`¿Eliminar el artículo "${item.title}"?`))return;await deleteKnowledgeArticle(item.id);await load();}}>Eliminar</Button></footer></article>)}</div>{!visible.length&&<div className="empty-state">No hay artículos que coincidan.</div>}
  {selected&&<Modal title={selected.title} onClose={()=>setSelected(null)} wide><div className="knowledge-reader"><div className="ticket-tags"><span>{selected.category}</span>{selected.tags.map(tag=><span key={tag}>{tag}</span>)}</div><iframe title={selected.title} sandbox="" srcDoc={`<!doctype html><meta charset="utf-8"><style>body{font:16px/1.6 system-ui;padding:8px;color:#172033}a{color:#2563eb}img{max-width:100%}pre{white-space:pre-wrap}</style>${selected.content}`}/>{!!selected.attachments.length&&<div className="knowledge-attachments">{selected.attachments.map((attachment,index)=><a key={`${attachment.url}-${index}`} href={attachment.url} target="_blank" rel="noreferrer">📎 {attachment.name}</a>)}</div>}</div></Modal>}
  {draft&&<Modal title={draft.id?'Editar artículo':'Nuevo artículo'} onClose={()=>setDraft(null)} wide><div className="knowledge-editor"><div className="grid-2"><label>Título<input className="input" value={draft.title||''} onChange={e=>setDraft(value=>({...value!,title:e.target.value}))}/></label><label>Categoría<input className="input" value={draft.category||''} onChange={e=>setDraft(value=>({...value!,category:e.target.value}))}/></label></div><label>Tags (separados por coma)<input className="input" value={(draft.tags||[]).join(', ')} onChange={e=>setDraft(value=>({...value!,tags:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)}))}/></label><div className="rich-editor"><div className="rich-toolbar"><button type="button" onClick={()=>document.execCommand('bold')}>Negrita</button><button type="button" onClick={()=>document.execCommand('italic')}>Cursiva</button><button type="button" onClick={()=>document.execCommand('insertUnorderedList')}>Lista</button><button type="button" onClick={()=>document.execCommand('formatBlock',false,'h2')}>Título</button></div><div key={draft.id||'new'} className="rich-content" contentEditable suppressContentEditableWarning dangerouslySetInnerHTML={{__html:draft.content||''}} onInput={e=>{const html=e.currentTarget.innerHTML;setDraft(value=>({...value!,content:html}));}}/></div><div className="knowledge-attachments">{(draft.attachments||[]).map((attachment,index)=><span key={`${attachment.url}-${index}`}><a href={attachment.url} target="_blank" rel="noreferrer">{attachment.name}</a><button onClick={()=>setDraft(value=>({...value!,attachments:(value?.attachments||[]).filter((_,i)=>i!==index)}))}>×</button></span>)}</div><label className="btn knowledge-upload">{uploading?'Subiendo…':'+ Adjuntar'}<input type="file" disabled={uploading} accept="image/*,.pdf,.docx,.xlsx,.txt" onChange={e=>void file(e.target.files?.[0])}/></label><div className="actions"><Button variant="primary" onClick={()=>void save()}>Guardar artículo</Button><Button onClick={()=>setDraft(null)}>Cancelar</Button></div></div></Modal>}
  </section>;
}
function read(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});}
function mime(name:string){const ext=name.split('.').pop()?.toLowerCase();return({pdf:'application/pdf',txt:'text/plain',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'} as Record<string,string>)[ext||'']||'application/octet-stream';}
function date(value:string){return value?String(value).slice(0,10).split('-').reverse().join('/'):'—';}
