/*
 * Migra techasset.db (SQLite) -> Supabase/Postgres.
 *
 * Uso:
 *   node migrate_to_postgres.cjs --dry-run                 # solo imprime el DDL Postgres, no conecta
 *   node migrate_to_postgres.cjs "postgresql://...:5432/postgres"   # crea tablas + carga datos
 *
 * Idempotente: hace DROP TABLE IF EXISTS ... CASCADE antes de crear.
 */
const path = require('path');
const Database = require('better-sqlite3');

const SQLITE_PATH = process.env.SQLITE_PATH || 'C:/Users/gonib/Downloads/techasset_export/techasset.db';
const arg = process.argv[2];
const DRY_RUN = arg === '--dry-run' || !arg;
const CONN = DRY_RUN ? null : arg;

// ---- mapeo de tipos SQLite -> Postgres (reglas de afinidad) ----
function pgType(sqliteType) {
  const t = (sqliteType || '').toUpperCase();
  if (t.includes('INT')) return 'BIGINT';
  if (t.includes('CHAR') || t.includes('CLOB') || t.includes('TEXT')) return 'TEXT';
  if (t.includes('BLOB') || t === '') return 'BYTEA';
  if (t.includes('REAL') || t.includes('FLOA') || t.includes('DOUB')) return 'DOUBLE PRECISION';
  if (t.includes('BOOL')) return 'SMALLINT';     // SQLite guarda 0/1
  if (t.includes('NUMERIC') || t.includes('DEC')) return 'NUMERIC';
  return 'TEXT'; // date/time/otros: SQLite los guarda como texto
}

const q = (id) => '"' + id.replace(/"/g, '""') + '"';

function buildSchema(db) {
  const tables = db.prepare(
    "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
  ).all().map(r => r.name);

  const ddl = [];
  const meta = {};
  for (const name of tables) {
    const cols = db.prepare(`PRAGMA table_info(${q(name)})`).all(); // cid,name,type,notnull,dflt_value,pk
    const createSql = db.prepare(
      "SELECT sql FROM sqlite_master WHERE type='table' AND name=?"
    ).get(name).sql;
    const isAutoInc = /AUTOINCREMENT/i.test(createSql);

    const pkCols = cols.filter(c => c.pk > 0).sort((a, b) => a.pk - b.pk).map(c => c.name);
    const lines = [];
    for (const c of cols) {
      let type = pgType(c.type);
      // PK entero autoincremental -> IDENTITY (permite insertar valores explícitos y autonumerar luego)
      if (isAutoInc && c.pk === 1 && type === 'BIGINT') {
        type = 'BIGINT GENERATED BY DEFAULT AS IDENTITY';
      }
      const notNull = c.notnull ? ' NOT NULL' : '';
      lines.push(`  ${q(c.name)} ${type}${notNull}`);
    }
    if (pkCols.length) {
      lines.push(`  PRIMARY KEY (${pkCols.map(q).join(', ')})`);
    }
    ddl.push(`DROP TABLE IF EXISTS ${q(name)} CASCADE;`);
    ddl.push(`CREATE TABLE ${q(name)} (\n${lines.join(',\n')}\n);`);
    meta[name] = { cols: cols.map(c => c.name), types: Object.fromEntries(cols.map(c => [c.name, pgType(c.type)])), autoIncPk: isAutoInc ? pkCols[0] : null };
  }
  return { tables, ddl, meta };
}

async function main() {
  const db = new Database(SQLITE_PATH, { readonly: true });
  const { tables, ddl, meta } = buildSchema(db);

  if (DRY_RUN) {
    console.log('-- ===== DRY RUN: DDL Postgres generado (no se conectó a ninguna base) =====\n');
    console.log(ddl.join('\n\n'));
    console.log(`\n-- ${tables.length} tablas listas para crear.`);
    db.close();
    return;
  }

  const { Client } = require('pg');
  const client = new Client({ connectionString: CONN, ssl: { rejectUnauthorized: false } });
  await client.connect();
  console.log('Conectado a Postgres. Creando esquema...');
  await client.query('BEGIN');
  try {
    for (const stmt of ddl) await client.query(stmt);

    let grandTotal = 0;
    for (const name of tables) {
      const rows = db.prepare(`SELECT * FROM ${q(name)}`).all();
      if (!rows.length) { console.log(`  ${name}: 0 filas`); continue; }
      const cols = meta[name].cols;
      const colList = cols.map(q).join(', ');
      const BATCH = 400;
      for (let i = 0; i < rows.length; i += BATCH) {
        const slice = rows.slice(i, i + BATCH);
        const values = [];
        const tuples = slice.map((row, ri) => {
          const ph = cols.map((c, ci) => {
            values.push(row[c]);
            return '$' + (ri * cols.length + ci + 1);
          });
          return '(' + ph.join(', ') + ')';
        });
        await client.query(
          `INSERT INTO ${q(name)} (${colList}) VALUES ${tuples.join(', ')}`,
          values
        );
      }
      // reajustar la secuencia IDENTITY al máximo id existente
      const pk = meta[name].autoIncPk;
      if (pk) {
        await client.query(
          `SELECT setval(pg_get_serial_sequence($1, $2), COALESCE((SELECT MAX(${q(pk)}) FROM ${q(name)}), 1))`,
          [name, pk]
        );
      }
      grandTotal += rows.length;
      console.log(`  ${name}: ${rows.length} filas`);
    }
    await client.query('COMMIT');
    console.log(`\n✅ Migración completa: ${grandTotal} filas en ${tables.length} tablas.`);
  } catch (e) {
    await client.query('ROLLBACK');
    console.error('❌ Error, se hizo ROLLBACK (no quedó nada a medias):', e.message);
    process.exitCode = 1;
  } finally {
    await client.end();
    db.close();
  }
}

main().catch(e => { console.error(e); process.exit(1); });
