import { useCallback, useEffect, useState } from 'react';
import type { Suggestion, SuggestionComment, SuggestionStats, SuggestionStatus } from '../../types';
import { addSuggestionComment, createSuggestion, deleteSuggestion, getSuggestionComments, getSuggestions, toggleSuggestionVote, updateSuggestion } from '../../services/suggestionsApi';
import { Button } from '../layout/Button';
import { Modal } from '../layout/Modal';
import { useAssistantContext } from '../../hooks/useAssistantContext';

const STATUSES: SuggestionStatus[] = ['Proposed','Under Review','Planned','In Progress','Implemented','Rejected'];
const STATUS_LABEL: Record<SuggestionStatus,string> = { Proposed:'Propuesta','Under Review':'En revisión',Planned:'Planificada','In Progress':'En progreso',Implemented:'Implementada',Rejected:'Rechazada' };
const EMPTY_STATS: SuggestionStats = { total:0,mostVoted:null,implemented:0,pendingReview:0 };

export function SuggestionsPage() {
  const [items,setItems]=useState<Suggestion[]>([]);
  const [stats,setStats]=useState<SuggestionStats>(EMPTY_STATS);
  const [categories,setCategories]=useState<string[]>([]);
  const [canManage,setCanManage]=useState(false);
  const [status,setStatus]=useState(''); const [category,setCategory]=useState(''); const [sort,setSort]=useState('newest');
  const [editing,setEditing]=useState<Suggestion|null>(null); const [formOpen,setFormOpen]=useState(false);
  const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [formCategory,setFormCategory]=useState('General');
  const [detail,setDetail]=useState<Suggestion|null>(null); const [comments,setComments]=useState<SuggestionComment[]>([]); const [comment,setComment]=useState('');
  useAssistantContext(detail?{type:'suggestion',id:String(detail.id),label:detail.title,data:{status:detail.status,category:detail.category,votes:detail.voteCount}}:null);
  const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState('');

  const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await getSuggestions({status,category,sort});setItems(response.items||[]);setStats(response.stats||EMPTY_STATS);setCategories(response.categories||[]);setCanManage(response.canManage);}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar las sugerencias.');}finally{setLoading(false);}},[status,category,sort]);
  useEffect(()=>{void load();},[load]);
  const openCreate=()=>{setEditing(null);setTitle('');setDescription('');setFormCategory('General');setFormOpen(true);};
  const openEdit=(item:Suggestion)=>{setEditing(item);setTitle(item.title);setDescription(item.description);setFormCategory(item.category);setFormOpen(true);};
  const save=async()=>{if(!title.trim()||!description.trim()){setError('Completá título y descripción.');return;}setBusy(true);try{if(editing)await updateSuggestion(editing.id,{title,description,category:formCategory});else await createSuggestion({title,description,category:formCategory});setFormOpen(false);await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}};
  const vote=async(item:Suggestion)=>{setItems(list=>list.map(current=>current.id===item.id?{...current,hasVoted:!current.hasVoted,voteCount:Math.max(0,current.voteCount+(current.hasVoted?-1:1))}:current));try{await toggleSuggestionVote(item.id);await load();}catch{await load();}};
  const openDetail=async(item:Suggestion)=>{setDetail(item);setComment('');try{const response=await getSuggestionComments(item.id);setComments(response.items||[]);}catch{setComments([]);}};
  const sendComment=async()=>{if(!detail||!comment.trim())return;setBusy(true);try{const response=await addSuggestionComment(detail.id,comment);setComments(list=>[...list,response.item]);setComment('');await load();}finally{setBusy(false);}};
  return <section className="view active suggestions-page">
    <div className="card-head suggestions-head"><div><h2>Sugerencias e ideas</h2><p className="muted">Propuestas visibles, votables y con seguimiento de avance.</p></div><Button variant="primary" onClick={openCreate}>Nueva sugerencia</Button></div>
    <div className="suggestion-kpis"><div><span>Total</span><strong>{stats.total}</strong></div><div><span>Más votada</span><strong>{stats.mostVoted?.votes??0}</strong><small>{stats.mostVoted?.title||'Sin votos'}</small></div><div><span>Implementadas</span><strong>{stats.implemented}</strong></div><div><span>Pendientes de revisión</span><strong>{stats.pendingReview}</strong></div></div>
    <section className="card suggestion-filters"><label>Estado<select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option>{STATUSES.map(item=><option value={item} key={item}>{STATUS_LABEL[item]}</option>)}</select></label><label>Categoría<select className="input" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas</option>{categories.map(item=><option key={item}>{item}</option>)}</select></label><label>Orden<select className="input" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Más nuevas</option><option value="most_voted">Más votadas</option></select></label></section>
    {error&&<div className="tool-error">{error}</div>}
    <div className="suggestion-grid">{items.map(item=><article className="card suggestion-card" key={item.id}><div className="suggestion-card-top"><span className={`suggestion-status status-${item.status.toLowerCase().replace(/\s/g,'-')}`}>{STATUS_LABEL[item.status]}</span><span className="muted">{item.category}</span></div><h3>{item.title}</h3><p>{item.description}</p><div className="suggestion-author">{item.authorName||item.authorEmail||'Usuario'} · {new Date(item.createdAt).toLocaleDateString('es-AR')}</div>{canManage&&<label className="suggestion-workflow">Estado<select className="input" value={item.status} onChange={async e=>{await updateSuggestion(item.id,{status:e.target.value as SuggestionStatus});await load();}}>{STATUSES.map(value=><option value={value} key={value}>{STATUS_LABEL[value]}</option>)}</select></label>}<div className="suggestion-actions"><button type="button" className={item.hasVoted?'active':''} onClick={()=>void vote(item)}>▲ {item.voteCount}</button><button type="button" onClick={()=>void openDetail(item)}>💬 {item.commentCount}</button>{item.canEdit&&<button type="button" onClick={()=>openEdit(item)}>Editar</button>}{item.canDelete&&<button type="button" onClick={async()=>{if(window.confirm('¿Eliminar esta sugerencia?')){await deleteSuggestion(item.id);await load();}}}>Eliminar</button>}</div></article>)}{!loading&&!items.length&&<div className="empty-state">No hay sugerencias para estos filtros.</div>}</div>
    {formOpen&&<Modal title={editing?'Editar sugerencia':'Nueva sugerencia'} onClose={()=>setFormOpen(false)}><div className="stack"><label>Título<input className="input" value={title} onChange={e=>setTitle(e.target.value)} maxLength={180}/></label><label>Categoría<input className="input" value={formCategory} onChange={e=>setFormCategory(e.target.value)} list="suggestion-categories"/><datalist id="suggestion-categories">{categories.map(item=><option key={item} value={item}/>)}</datalist></label><label>Descripción<textarea className="input" rows={8} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="actions"><Button onClick={()=>setFormOpen(false)}>Cancelar</Button><Button variant="primary" disabled={busy} onClick={()=>void save()}>{busy?'Guardando...':'Guardar'}</Button></div></div></Modal>}
    {detail&&<Modal title={detail.title} onClose={()=>setDetail(null)}><div className="suggestion-detail"><p>{detail.description}</p><div className="suggestion-comments">{comments.map(item=><article key={item.id}><strong>{item.authorName||item.authorEmail||'Usuario'}</strong><span>{new Date(item.createdAt).toLocaleString('es-AR')}</span><p>{item.body}</p></article>)}{!comments.length&&<div className="empty-state">Todavía no hay comentarios.</div>}</div><label>Comentar<textarea className="input" rows={3} value={comment} onChange={e=>setComment(e.target.value)}/></label><div className="actions"><Button variant="primary" disabled={busy||!comment.trim()} onClick={()=>void sendComment()}>Publicar comentario</Button></div></div></Modal>}
  </section>;
}
