import { useState } from 'react';
import type { TicketTemplate } from '../../types';
import { createTicketTemplate, deleteTicketTemplate, updateTicketTemplate } from '../../services/ticketsApi';
import { Modal } from '../layout/Modal';
import { Button } from '../layout/Button';

const EMPTY: Partial<TicketTemplate> = { title:'',description:'',priority:'Media',category:'',suggestedAssignee:'',checklist:[],tags:[] };

export function TicketTemplateManager({templates,onClose,onChanged}:{templates:TicketTemplate[];onClose:()=>void;onChanged:()=>Promise<void>}){
  const [draft,setDraft]=useState<Partial<TicketTemplate>|null>(null);
  const [editing,setEditing]=useState<number|null>(null);
  const open=(item?:TicketTemplate)=>{setEditing(item?.id||null);setDraft(item?{...item}: {...EMPTY});};
  const save=async()=>{if(!draft?.title?.trim())return;if(editing)await updateTicketTemplate(editing,draft);else await createTicketTemplate(draft);setDraft(null);setEditing(null);await onChanged();};
  return <Modal title="Plantillas de tickets" onClose={onClose} wide><div className="ticket-template-manager"><p className="muted">Guardá incidentes frecuentes con prioridad, categoría, responsable sugerido, tags y checklist.</p><div className="ticket-template-grid">{templates.map(item=><article className="card" key={item.id}><header><div><strong>{item.title}</strong><span>{item.category||'Sin categoría'} · {item.priority}</span></div><div className="actions"><Button onClick={()=>open(item)}>Editar</Button><Button onClick={async()=>{await deleteTicketTemplate(item.id);await onChanged();}}>Eliminar</Button></div></header><p>{item.description||'Sin descripción'}</p>{!!item.checklist.length&&<small>{item.checklist.length} pasos · {item.checklist.join(' · ')}</small>}{!!item.tags.length&&<div className="ticket-tags">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div>}</article>)}</div>{!draft&&<Button variant="primary" onClick={()=>open()}>+ Nueva plantilla</Button>}{draft&&<div className="card ticket-template-form"><div className="grid-2"><label>Título<input className="input" value={draft.title||''} onChange={e=>setDraft(value=>({...value!,title:e.target.value}))}/></label><label>Categoría<input className="input" value={draft.category||''} onChange={e=>setDraft(value=>({...value!,category:e.target.value}))}/></label></div><label>Descripción<textarea className="input" rows={3} value={draft.description||''} onChange={e=>setDraft(value=>({...value!,description:e.target.value}))}/></label><div className="grid-2"><label>Prioridad<select className="input" value={draft.priority||'Media'} onChange={e=>setDraft(value=>({...value!,priority:e.target.value}))}><option>Baja</option><option>Media</option><option>Alta</option><option>Urgente</option></select></label><label>Responsable sugerido<input className="input" value={draft.suggestedAssignee||''} onChange={e=>setDraft(value=>({...value!,suggestedAssignee:e.target.value}))}/></label></div><label>Checklist (un paso por línea)<textarea className="input" rows={4} value={(draft.checklist||[]).join('\n')} onChange={e=>setDraft(value=>({...value!,checklist:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean)}))}/></label><label>Tags (separados por coma)<input className="input" value={(draft.tags||[]).join(', ')} onChange={e=>setDraft(value=>({...value!,tags:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)}))}/></label><div className="actions"><Button variant="primary" onClick={()=>void save()}>Guardar</Button><Button onClick={()=>setDraft(null)}>Cancelar</Button></div></div>}</div></Modal>;
}
